### ISSUE TITLE
米游社接口报错:

### ISSUE THREAD

**Issue by Fahaxikiii** [SilveryStar/Adachi-BOT#103]
### 系统版本

Windows Server 2012 R2 DataCenter 64bitCN

### Node.js 版本

16.13.0

### 应用版本

2.2.0

### 配置文件

```YAML
silvery-star.abyss:
  type: switch
  auth: 1
  scope: 3
  mode: divided
  onKey: 深渊
  offKey: 上期深渊
  header: ""
  enable: true
```

### 错误报告

```Text
米游社接口报错: invalid input format: strconv.ParseUint: parsing "NaN": invalid syntax, key=uid
```
