### ISSUE TITLE
查询uid时，返回输入 UID 不合法

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#104]
### 系统版本

Windows 10 专业工作站版 1909

### Node.js 版本

v13.13.0

### 应用版本

v2.2.0

### 启动方式

Forever

### 复述操作

输入UID 123456789，回复“输入 UID 不合法”
输入Uid 123456789，回复“输入 UID 不合法”
输入uid 123456789，正常

### 配置文件

```YAML
修改过commands.yml

silvery-star.uid-query:
  type: order
  auth: 1
  scope: 3
  headers:
    - uid
    - UID
    - Uid
  enable: true
```

### 错误报告

```Text
无错误报告
```
