### ISSUE TITLE
修改登录方式后仍是安卓登录

### ISSUE THREAD

**Issue by VsentCN** [SilveryStar/Adachi-BOT#105]
### 系统版本

Windows Server 2019 DataCenter 64bitCN

### Node.js 版本

13.13.0

### 应用版本

2.2.0

### 启动方式

Forever

### 复述操作

无

### 配置文件

```YAML
qrcode: false
number: xxxx
password: "xxxx"
master: xxxx
header: ""
platform: 3
atUser: false
inviteAuth: master
countThreshold: 60
groupIntervalTime: 3000
privateIntervalTime: 6000
helpMessageStyle: forward
logLevel: info
dbPort: 6379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "88888888"
```

### 错误报告

```Text
[INFO] [Android:
修改登录方式后仍是安卓登录
```
