### ISSUE TITLE
私人服务模块，添加Cookie时提示“米游社接口报错：Please login”

### ISSUE THREAD

**Issue by pkuislm** [SilveryStar/Adachi-BOT#114]
### 系统版本

Centos 7 x64

### Node.js 版本

v12.22.7

### 应用版本

2.2.0-bugfix1

### 启动方式

Docker

### 复述操作

私聊中发送ps指令，提示将要开启私人服务，然后发送confirm+cookies信息。机器人随即提示“米游社接口报错：Please login”。

### 配置文件

```YAML
setting.yml:
qrcode: false
number: ******
password: "***"
master: ******
header: ""
platform: 3
atUser: false
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpMessageStyle: message
logLevel: info
dbPort: 56379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "********"

cookies.yml:
cookies:
 - _MHYUUID=******************
```

### 错误报告

```Text
控制台无错误输出
```
