### ISSUE TITLE
一个应该算是无关紧要的问题,使用2.2.1的米游社查询时,查询界面格式与设置不符

### ISSUE THREAD

**Issue by Cn7ci4** [SilveryStar/Adachi-BOT#120]
### 系统版本

windows 11 企业版 22000.348

### Node.js 版本

17.1.0

### 应用版本

2.2.1

### 复述操作

配置文件为weaponA,输入指令mys时,显示格式为weaponB;
输入指令uid时,显示格式为weaponA.
![image](https://user-images.githubusercontent.com/32661244/143724310-4f4b5229-0bef-4495-bf10-977662960d0b.png)
![image](https://user-images.githubusercontent.com/32661244/143724315-0f0738f3-7014-41b9-b865-46700b1bf72b.png)

### 配置文件

```YAML
genshin.yml
cardWeaponStyle: weaponA
serverPort: 58612
```

### 错误报告

```Text
无
```
