### ISSUE TITLE
mac环境报Error: Could not find expected browser (chrome) locally

### ISSUE THREAD

**Issue by NiHang** [SilveryStar/Adachi-BOT#121]
### 系统版本

macOS 11.4

### Node.js 版本

v15.14.0

### 应用版本

2.2.1-bugfix1

### 启动方式

Docker

### 复述操作

QQ发送消息help呼出菜单如下：
Adachi-BOT v2.2.1~
1. 指令帮助 help (-k)
2. 管理设置 manager|unmanaged [qq]
3. 封禁用户 ban|unban [qq|群号]
4. 指令权限 limit [qq|群号] [key] [on|off]
5. 操作冷却 int [qq|群号] [时间]
6. 掷骰  r(次数)d[面数]k(前k大)

使用 detail+指令编号 获取更多信息
[] 表示必填, () 表示选填, | 表示选择

怎么修改这个菜单？我修改了commands.yml增加了silvery-star.uid-query并未生效。能不能提供给全的默认配置指令？

### 配置文件

```YAML
tips: 此文件修改后需重启应用
adachi.help:
  type: order
  auth: 1
  scope: 3
  headers:
    - help
  enable: true
adachi.detail:
  type: order
  auth: 1
  scope: 3
  headers:
    - detail
  enable: true
adachi.manager:
  type: switch
  auth: 3
  scope: 3
  mode: divided
  onKey: manager
  offKey: unmanaged
  header: ""
  enable: true
adachi.ban:
  type: switch
  auth: 2
  scope: 3
  mode: divided
  onKey: ban
  offKey: unban
  header: ""
  enable: true
adachi.limit:
  type: switch
  auth: 2
  scope: 3
  mode: single
  onKey: on
  offKey: off
  header: limit
  enable: true
adachi.interval:
  type: order
  auth: 2
  scope: 3
  headers:
    - int
  enable: true
tools.dice:
  type: order
  auth: 1
  scope: 3
  headers:
    - __
  enable: true
silvery-star.uid-query:
  type: order
  auth: 1
  scope: 3
  headers:
    - uid
  enable: true
```
