### ISSUE TITLE
Bot密码如果最后一位是#则会被截掉不传输

### ISSUE THREAD

**Issue by BennettChina** [SilveryStar/Adachi-BOT#123]
### 系统版本

centos8+docker 19.03.13

### Node.js 版本

v17.2.0

### 应用版本

2.2.1-bugfix1

### 启动方式

Docker

### 复述操作

按照文档的部署方式，执行 `npm install yaml oicq` 后提示需要 `npm audit fix`，执行了一次 `npm audit fix`。然后继续login，login成功后通过docker-compose启动。

### 配置文件

```YAML
`setting.yml`


qrcode: false
number: ***********
password: "***********#"
master: ***********
header: "#"
platform: 4
atUser: false
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpMessageStyle: message
logLevel: info
dbPort: 56379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "************"
```

### 错误报告

```Text
web console登录失败，提示账号密码错误。查看网络请求发现密码最后一位的"#"丢失。（吐槽：Get方式登录，明文传输信息。。。）
```
