### ISSUE TITLE
米游社签到部分账号报错，实际没签到上

### ISSUE THREAD

**Issue by deYangar** [SilveryStar/Adachi-BOT#150]
### 系统版本

Windows 10 专业版 21H1

### Node.js 版本

v13.13.0

### 应用版本

2.2.5-bugfix2

### 启动方式

Forever

### 复述操作

一个号是19号早上8点的时候报错的，另一个是20号，两个不同的号
另外确定cookie没问题，前一天和后一天都能正常签到
至于具体能否签到上，暂时不确定，因为只有两个号遇到了这样的情况，一个号主说签上了，一个号主说没有

另外控制台没报错
![QQ截图20211221235144](https://user-images.githubusercontent.com/70438628/146959786-48ca37f2-d537-4868-bc6c-2cea0fc1292f.jpg)

### 配置文件

```YAML
commands.yml

silvery-star.private-toggle-sign:
  type: order
  auth: 1
  scope: 3
  headers:
    - mysqd
    - 米游社签到
  enable: true
```

### 错误报告

```Text
无
```
