### ISSUE TITLE
Windows 下直接启动无法使用 web console

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#155]
### 系统版本

Windows 10 Pro (19043.1348)

### Node.js 版本

12.22.7

### 应用版本

2.2.5

### 复述操作

设置下述配置文件后在 Windows Terminal (Powershell 7) 中以 `npm run start` 启动，无法使用 web console，终端有输出。

### 配置文件

```YAML
qrcode: false
number: 
password: 
master: 
header: /
platform: 5
atUser: false
dbPort: 56379
inviteAuth: master
groupIntervalTime: 1500
privateIntervalTime: 1000
helpMessageStyle: message
logLevel: info
webConsole:
  - enable: true
  - consolePort: 58526
  - tcpLoggerPort: 54921
  - jwtSecret: 
atBOT: false
```

### 错误报告

```Text
无错误报告
```
