### ISSUE TITLE
机器人收不到消息

### ISSUE THREAD

**Issue by Hara-J** [SilveryStar/Adachi-BOT#157]
### 系统版本

CentOS7.5

### Node.js 版本

v16.13.1

### 应用版本

V2.2.6

### 启动方式

Docker

### 复述操作

机器人收不到消息，第一次刚部署时可以接收到，运行一段时间后就接收不到了，然后再过段时间又可以接收，日志无报错，只有刚部署的一条警告，国内服务器

### 配置文件

```YAML
qrcode: false
number: ****
password: ***
master: ***
header: ""
platform: 3
atUser: true
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpMessageStyle: forward
logLevel: info
dbPort: 56379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: a1***44
atBOT: false
```

### 错误报告

```Text
[WARN] - 探索服务器失败: timeout
```
