### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:56379

### ISSUE THREAD

**Issue by 12123ads** [SilveryStar/Adachi-BOT#163]
### 系统版本

debian11

### Node.js 版本

v14.18.3

### 应用版本

2.2.7

### 启动方式

Forever

### 复述操作

root@instance-20220109-2114:~/Adachi-BOT# docker ps
CONTAINER ID   IMAGE         COMMAND                  CREATED         STATUS         PORTS      NAMES
2177c4a6f3ab   redis:6.2.3   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes   6379/tcp   adachi-redis
===================================================
root@instance-20220109-2114:~/Adachi-BOT# npm start

> adachi-bot@2.2.7 start /root/Adachi-BOT
> ts-node -r tsconfig-paths/register app.ts --files

Error: connect ECONNREFUSED 127.0.0.1:56379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adachi-bot@2.2.7 start: `ts-node -r tsconfig-paths/register app.ts --files`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adachi-bot@2.2.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-11T10_05_48_054Z-debug.log
===========================================================
root@instance-20220109-2114:~/Adachi-BOT# docker logs 2177c4a6f3ab
1:C 11 Jan 2022 09:18:49.456 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Jan 2022 09:18:49.456 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Jan 2022 09:18:49.456 # Configuration loaded
1:M 11 Jan 2022 09:18:49.457 * monotonic clock: POSIX clock_gettime
1:M 11 Jan 2022 09:18:49.457 * Running mode=standalone, port=56379.
1:M 11 Jan 2022 09:18:49.457 # Server initialized
1:M 11 Jan 2022 09:18:49.457 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 11 Jan 2022 09:18:49.458 * Ready to accept connections
1:signal-handler (1641893973) Received SIGTERM scheduling shutdown...
1:M 11 Jan 2022 09:39:33.846 # User requested shutdown...
1:M 11 Jan 2022 09:39:33.849 * Calling fsync() on the AOF file.
1:M 11 Jan 2022 09:39:33.860 * Saving the final RDB snapshot before exiting.
1:M 11 Jan 2022 09:39:33.863 * DB saved on disk
1:M 11 Jan 2022 09:39:33.863 # Redis is now ready to exit, bye bye...
1:C 11 Jan 2022 09:39:35.054 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Jan 2022 09:39:35.054 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Jan 2022 09:39:35.054 # Configuration loaded
1:M 11 Jan 2022 09:39:35.054 * monotonic clock: POSIX clock_gettime
1:M 11 Jan 2022 09:39:35.055 * Running mode=standalone, port=56379.
1:M 11 Jan 2022 09:39:35.055 # Server initialized
1:M 11 Jan 2022 09:39:35.055 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 11 Jan 2022 09:39:35.055 * Ready to accept connections

### 配置文件

```YAML
stteing.yml：
qrcode: false
number: ***
password:***
master: ***
header: "#"
platform: 2
atUser: false
inviteAuth: master
countThreshold: 60
groupIntervalTime: 150
privateIntervalTime: 200
helpMessageStyle: forward
logLevel: debug
dbPort: 56379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: 114514abc
atBOT: fals
================================================
redis.yml：
stop-writes-on-bgsave-error no
rdbcompression no
dbfilename dump.rdb

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

port 56379
dir /data/
```

### 错误报告

```Text
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v14.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle adachi-bot@2.2.7~prestart: adachi-bot@2.2.7
6 info lifecycle adachi-bot@2.2.7~start: adachi-bot@2.2.7
7 verbose lifecycle adachi-bot@2.2.7~start: unsafe-perm in lifecycle true
8 verbose lifecycle adachi-bot@2.2.7~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/Adachi-BOT/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle adachi-bot@2.2.7~start: CWD: /root/Adachi-BOT
10 silly lifecycle adachi-bot@2.2.7~start: Args: [ '-c', 'ts-node -r tsconfig-paths/register app.ts --files' ]
11 silly lifecycle adachi-bot@2.2.7~start: Returned: code: 1  signal: null
12 info lifecycle adachi-bot@2.2.7~start: Failed to exec start script
13 verbose stack Error: adachi-bot@2.2.7 start: `ts-node -r tsconfig-paths/register app.ts --files`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid adachi-bot@2.2.7
15 verbose cwd /root/Adachi-BOT
16 verbose Linux 5.10.0-10-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.18.3
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error adachi-bot@2.2.7 start: `ts-node -r tsconfig-paths/register app.ts --files`
22 error Exit status 1
23 error Failed at the adachi-bot@2.2.7 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
