### ISSUE TITLE
查询深渊caby指令报错

### ISSUE THREAD

**Issue by LinYingLY** [SilveryStar/Adachi-BOT#175]
### 系统版本

Windows（Microsoft Windows Server 2019 Datacenter）

### Node.js 版本

16.13.2

### 应用版本

2.2.8-bugfix2

### 复述操作

查询深渊caby指令错误 前几天用的还好好的 今天就报错了 怪了
然后我用自己的笔记本跑了一遍没有问题但是私聊发的图全是裂的

### 配置文件

```YAML
settings.yml
qrcode: false
number: **********
password: ************
master: *********
header: .
platform: 3
atUser: true
inviteAuth: user
countThreshold: 60
groupIntervalTime: 1000
privateIntervalTime: 1000
helpMessageStyle: message
logLevel: info
dbPort: 6379
webConsole:
  enable: true
  consolePort: 11451
  tcpLoggerPort: 54921
  jwtSecret: "12345"
atBOT: false

还有cookie也改了 其他全没动过
```

### 错误报告

```Text
[01:55:07.771] [Watch:*****] [ERROR] [Event] TypeError: Cannot read properties of undefined (reading 'setting')
    at Switch.<anonymous> (C:\Users\Administrator\Desktop\Adachi-BOT-master\src\plugins\genshin\achieves\private\query\abyss.ts:24:31)
    at step (C:\Users\Administrator\Desktop\Adachi-BOT-master\src\plugins\genshin\achieves\private\query\abyss.ts:33:23)
    at Object.next (C:\Users\Administrator\Desktop\Adachi-BOT-master\src\plugins\genshin\achieves\private\query\abyss.ts:14:53)
    at fulfilled (C:\Users\Administrator\Desktop\Adachi-BOT-master\src\plugins\genshin\achieves\private\query\abyss.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
