### ISSUE TITLE
docker使用命令启动后没有反应

### ISSUE THREAD

**Issue by ZhangWY0724** [SilveryStar/Adachi-BOT#196]
### 系统版本

centos7.8

### Node.js 版本

14.17.6

### 应用版本

2.2.10-bugfix1

### 启动方式

Docker

### 复述操作

输入命令 docker-compose start
提示  
Starting redis ... done
Starting bot   ... done
就没有后续了，访问网页也无法打开
采用npm start就可以启动成功，并且发送消息正常，但是关闭窗口后，就无法使用了

### 配置文件

```YAML
qrcode: false
number: 10947204
password: *******
master: 1024516151
header: "#"
platform: 1
atUser: true
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpMessageStyle: message
logLevel: info
dbPort: 56379
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: "112233"
atBOT: false
```

### 错误报告

```Text
暂无错误报告
```
