### ISSUE TITLE
服务器端webConsole无法查询到日志

### ISSUE THREAD

**Issue by hyyy1211** [SilveryStar/Adachi-BOT#199]
### 系统版本

Alibaba Cloud Linux 3.21.04

### Node.js 版本

v16.14.0

### 应用版本

2.2.9-bugfix4

### 启动方式

Docker

### 复述操作

使用阿里云部署，可以QQ交互，在服务器端可以正常查到.log文件，但是在webConsole上面未能找到当天日志

### 配置文件

```YAML
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  jwtSecret: awa******
```
