### ISSUE TITLE
抽卡功能异常

### ISSUE THREAD

**Issue by MomentQYC** [SilveryStar/Adachi-BOT#256]
### 系统版本

Ubuntu 20.04

### Node.js 版本

16.15.1

### 应用版本

2.4.1

### 启动方式

Forever

### 复述操作

单纯启动，每次启动都会报错
已知可导致wish无法使用

### 配置文件

```YAML
tip: 前往 https://docs.adachi.top/config 查看配置详情
qrcode: false
number: *
password: *
master: *
header: ""
platform: 4
atUser: false
atBOT: false
addFriend: true
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1000
privateIntervalTime: 1500
helpMessageStyle: message
logLevel: info
dbPort: *
dbPassword: *
webConsole:与控制台无关
```

### 错误报告

```Text
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /path/to/bot/src/plugins/genshin/utils/api.ts:249:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
