### ISSUE TITLE
genshin插件uid指令报错

### ISSUE THREAD

**Issue by kressety** [SilveryStar/Adachi-BOT#299]
### 系统版本

Debian 10.4

### Node.js 版本

v10.24.0

### 应用版本

2.6.6

### 启动方式

Docker

### 复述操作

# QQ交互界面
> 人类: /bind xxxxxxxx (我的原神UID)

> Bot: 游戏UID绑定成功

> 人类: /uid xxxxxxxx (我的原神UID, 同上)

> Bot: SyntaxError: Unexpected token u in JSON at position 0

> 人类: /uid @人类 (我自己)

> Bot: SyntaxError: Unexpected token u in JSON at position 0

> 人类: /uid

> Bot: SyntaxError: Unexpected token u in JSON at position 0

### 配置文件

```YAML
setting.yml
    header: /
    webConsole.consolePort: 2023

docker-compose.yml
    services.bot.ports: "2023:80"
```

### 错误报告

```Text
试图通过/uid指令查询原神角色信息，bot回报SyntaxError
```
