### ISSUE TITLE
图片渲染异常

### ISSUE THREAD

**Issue by ddsb520** [SilveryStar/Adachi-BOT#315]
### 系统版本

Windows Server 2019 Standard 1809

### Node.js 版本

v16.18.0

### 应用版本

2.7.7

### 复述操作

#帮助

### 配置文件

```YAML
tip: 前往 https://docs.adachi.top/config 查看配置详情
qrcode: false
number: 3476239594
password: *****
master: 2235787316
header: "#"
platform: 1
atUser: false
atBOT: false
addFriend: true
useWhitelist: false
fuzzyMatch: true
matchPrompt: true
inviteAuth: master
countThreshold: 60
groupIntervalTime: 1500
privateIntervalTime: 2000
helpPort: 54919
helpMessageStyle: card
callTimes: 3
logLevel: info
dbPort: 6379
dbPassword: ""
webConsole:
  enable: true
  consolePort: 80
  tcpLoggerPort: 54921
  logHighWaterMark: 64
  jwtSecret: Q(/%nU-F,<n!{xwu
autoChat:
  tip1: type参数说明：1为青云客，不用配置后面的两个secret，
  tip2: 2为腾讯自然语言处理，需要前往腾讯云开通NLP并获取到你的secret（听说超级智能）
  enable: false
  type: 1
  secretId: ""
  secretKey: ""
```

### 错误报告

```Text
图片渲染错误
```
