### ISSUE TITLE
开发者你好 ! 关于Adachi-BOT 插件无法执行生命周期问题

### ISSUE THREAD

**Issue by Passerby-Fu** [SilveryStar/Adachi-BOT#354]
### 系统版本

win10

### Node.js 版本

16.14

### 应用版本

3.3.2

### 启动方式

None

### 复述操作

本地环境启动后 , 日志正常打印插件加载 , 但是在插件生命周期内打印或者断点 , 无法进入方法内
以下是插件内配置信息
`
export default definePlugin( {
	name: "aaaaa",
	cfgList: [  ],
	mounted() {
		console.log( "[aaaaa] 插件初始化")
	}
} );
`
以下是运行后日志截图
![image](https://github.com/user-attachments/assets/ad6f7ed0-5326-4766-a499-7bf3278439cb)

### 配置文件

```YAML
base.yml-->
reverseClient: false
wsServer: 127.0.0.1:15630
wsApiServer: ""
wsPort: 11451
master: 
inviteAuth: 2
logLevel: info
atUser: false
atBOT: false
addFriend: true
apiTimeout: 20000
renderPort: 9090
```
