### ISSUE TITLE
实时便笺相关功能错误

### ISSUE THREAD

**Issue by Autumn-of-One** [SilveryStar/Adachi-BOT#82]
### 环境
- 系统：Windows Server 2012 R2 DataCenter 64bitCN，linux试了一晚上也没成功，只好用windows了
- node 版本：v13.13.0
- bot 版本：v2.1.11

### 操作复述

1. commands.yml文件替换为了中文版本。
2. 在commands.yml中修改auth的值为2或3，机器人返回“发生未知错误”，修改为1正常。
3. 为命令添加多个触发词头时只有第一个生效，例：
```
-添加服务
-增加服务
```
只有第一个“添加服务”生效
### 配置文件

```
silvery-star.private-subscribe:
  type: order
  auth: 1
  scope: 2
  enable: true
  headers:
    - 添加服务
    - 增加服务
silvery-star.private-confirm:
  type: order
  auth: 1
  scope: 2
  enable: true
  headers:
    - 确认
silvery-star.private-list:
  type: order
  auth: 1
  scope: 2
  enable: true
  headers:
    - 服务列表
silvery-star.cancel-private:
  type: order
  auth: 1
  scope: 2
  enable: true
  headers:
    - 取消服务
```
