### ISSUE TITLE
2.2.0-Beta1 无法使用 `forever` 启动

### ISSUE THREAD

**Issue by AzusaYukina** [SilveryStar/Adachi-BOT#96]
### 环境
- 系统：Windows 10 Pro
- node 版本：12.22.7
- bot 版本：2.2.0-Beta1

### 操作复述

完整 clone 仓库并初始化后，将原始 config 文件夹复制到新文件夹，添加了有关 webconsole 配置。随后使用 `npm run start` 生成配置文件，但使用 `npm run serve` 无法启动。

### 配置文件

`setting.yml`
```
qrcode: false                # 是否启用扫码登录
                             # 每次登录都需验证,Docker启动禁用,默认不启用
number:                      # QQ 账号
password: ""                 # QQ 密码
master:                      # BOT 持有者账号
header: "/"                  # 命令起始符(可为空串"")
platform: 5                  # 登录平台
                             # 1.安卓手机(默认) 2.aPad 3.安卓手表 4.MacOS 5.iPad
atUser: false                # 是否启用回复时@用户, 默认关闭
dbPort: 56379                # 数据库端口
                             # 修改该选项需同时修改 redis.conf -> port
inviteAuth: "master"         # 邀请自动入群权限
                             # master表示BOT持有者, manager表示BOT管理员, 默认master
groupIntervalTime: 1500      # 群聊指令操作冷却时间, 单位毫秒, 默认 1500ms
privateIntervalTime: 10000   # 私聊指令操作冷却时间, 单位毫秒, 默认 2000ms
helpMessageStyle: message    # 帮助信息样式, 分为 message, forward, xml 三种
                             # 默认为 message. xml 疑似有封号风险, 谨慎使用, 大群勿用
logLevel: info
webConsole:
  - enable: true
  - consolePort: [隐去]
  - tcpLoggerPort: 54921
  - jwtSecret: [隐去]

# intervalTime: 1500           [已弃用]指令操作冷却时间, 单位毫秒, 默认1500ms
#                              [向后兼容]当仅配置该项, 上两项未配置时, 群聊/私聊冷却时间均设为该项
```

### 错误报告
无错误报告，输出如下：
```
 User@PC  D:          Adachi-BOT  web_console_dev  255  npm run serve

> adachi-bot@2.2.0-Beta1 serve D:\Adachi-BOT
> forever start --minUptime 1000 --spinSleepTime 1000 -v -c ts-node -r tsconfig-paths/register app.ts --files

info:    Forever processing file: app.ts
 User@PC  D:          Adachi-BOT  web_console_dev 
```
